landing/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^view-domains/$','landing.views.view_domains'),
	url(r'^add-node/$','landing.views.add_node',name="add-node"),
	url(r'^update-vpsnode/$','landing.views.vpsnode_update_view',name="update-vps-node"),
	url(r'^add-domain/$','landing.views.add_domain',name="add-domain"),
	url(r'^config-domain/$','landing.views.config_domain_view',name="config-domain"),
	url(r'^view-logs/$','landing.views.view_nodes',name="view_nodes"),
	url(r'^view-dns-hosts/$','landing.views.view_dns_hosts',name="view_dns_hosts"),
	url(r'^view_node/(?P<node_id>\d+)/$','landing.views.view_node'),
	url(r'^edit-domain/$','landing.views.edit_domain',name="edit-domain"),
	url(r'^add-domain-bulk/$','landing.views.add_domain_bulk',name="add-domain-bulk"),
)

nikolaproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'landing.views.home', name='home'),
    url(r'^landing/',include('landing.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/$','landing.views.logout',name="logout"),
)

landing/models.py
from django.db import models
from django.contrib.auth.models import User
STATUS = (
            ('available', 'available'),
            ('notavailable', 'notavailable'),
    )
NODE_STATUS = (
            ('Used', 'used'),
            ('Unused', 'unused'),
            ('Failed', 'failed'),
    )
RECORD_TYPES = (
        ('A','A (Address)'),
        ('TXT','TXT Record'),
    )
class Vpsnode(models.Model):
    ip_address = models.IPAddressField(max_length=254,)
    domain_name = models.CharField(max_length=255,unique=True)
    reverse_domain = models.CharField(max_length=200,)
    host_url = models.URLField(max_length=250,blank=True,)
    account_email = models.EmailField(max_length=100,blank=True,)
    account_password = models.CharField(max_length=50,blank=True,)
    root_password = models.CharField(max_length=50,blank=True,)
    cpanel_url = models.URLField(max_length=250,blank=True,)
    cpanel_username = models.CharField(max_length=50,blank=True,)
    cpanel_password = models.CharField(max_length=50,blank=True,)
    price = models.CharField(blank=True,max_length=50)
    notes = models.TextField(max_length=1000,blank=True,)
    status = models.CharField(max_length=50,choices=NODE_STATUS,
                              default="unused")
    comment = models.TextField(max_length=1000,blank=True,null=True)
    date_added = models.DateField(max_length=255,blank=True,
                                  auto_now_add=True)

    def __init__(self, *args, **kwargs):
        super(Vpsnode, self).__init__(*args, **kwargs)
        self.args = args

    def __unicode__(self):
        return self.reverse_domain

    class Meta():
        ordering = ('reverse_domain',)
        verbose_name = "Vpsnode"
        verbose_name_plural = "Vpsnodes"

class NamecheapAccount(models.Model):
    namecheap_api_key = models.CharField(max_length="255",)
    namecheap_username = models.CharField(max_length="100",)

class Ip_Address(models.Model):
    ip_address = models.IPAddressField(max_length=255)

    def __init__(self, *args, **kwargs):
        super(Ip_Address, self).__init__(*args, **kwargs)
        self.args = args

    def __unicode__(self):
        return self.ip_address

    class Meta():
        verbose_name = "IP Adress"
        verbose_name_plural = "IP Adresses"

class Domain(models.Model):
    domain_name = models.CharField(max_length=50, unique=True)
    subdomain_name = models.CharField(max_length=50,blank=True,null=True)
    ip_address = models.IPAddressField(max_length=255,blank=True,null=True)
    date_added = models.DateField(auto_now_add=True,blank=True)
    availability = models.CharField(max_length=50,choices=STATUS,
                                    blank=True,default="available")

    def __init__(self, *args, **kwargs):
        super(Domain, self).__init__(*args, **kwargs)
        self.args = args

    def __unicode__(self):
        return self.domain_name

    class Meta():
        ordering = ('-date_added','-availability',)
        verbose_name = "domain"
        verbose_name_plural = "domains"

class DomainConfiguration(models.Model):
    domain = models.OneToOneField(Domain)
    last_updated = models.DateField(auto_now=True)

class Host(models.Model):
    """This is a host setting for a domain configuration."""
    domain_conf = models.ForeignKey(DomainConfiguration)
    host_name = models.CharField(max_length=250)
    ip_address = models.CharField(max_length=255)
    record_type = models.CharField(max_length=255)
    ttl = models.PositiveIntegerField(max_length=255,default=1800)

class Subdomain(models.Model):
    """This is one subdomain setting for a domain configuration."""
    domain_conf = models.ForeignKey(DomainConfiguration)
    host_name = models.CharField(max_length=250)
    ip_address = models.CharField(max_length=255)
    record_type = models.CharField(max_length=255)
    ttl = models.PositiveIntegerField(max_length=255,default=1800)

class GoogleCredential(models.Model):
    google_username = models.CharField(max_length=250)
    google_pw = models.CharField(max_length=250)
    spreadsheetname = models.CharField(max_length=250)

landing/forms.py
from django import forms
from django.forms import ModelForm

from landing.models import Vpsnode, Domain


NODE_STATUS = (
            ('used', 'used'),
            ('unused', 'unused'),
            ('failed', 'failed'),
    )

class VpsnodeForm(ModelForm):
    class Meta:
        account_password = forms.CharField(widget=forms.PasswordInput)
        model = Vpsnode
        fields = ['ip_address','domain_name','reverse_domain','host_url',
                  'account_email','account_password','root_password',
                  'cpanel_url','cpanel_username','cpanel_password','price','notes','comment','status']


class DomainForm(ModelForm):
    class Meta:
        model = Domain
        fields = ['domain_name','availability']

class DomainConfigForm(ModelForm):
    class Meta:
        model = Domain
        fields = ['domain_name','subdomain_name','ip_address','availability',]

    def __init__(self, *args, **kwargs):
      super(DomainConfigForm, self).__init__(*args, **kwargs)
      self.fields["subdomain_name"].required = True
      self.fields["ip_address"].required = True

landing/views.py
import requests
import gspread
import random
import os
import socket

from landing.scripts import Api,ENDPOINTS,NAMESPACE,gen_hosts,record,keys
from landing.forms import VpsnodeForm,DomainForm,DomainConfigForm
from landing.models import GoogleCredential,Domain,Vpsnode,NamecheapAccount,Ip_Address
from landing.models import Domain as DomainModel

from django.contrib.auth import authenticate,login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms.formsets import formset_factory, BaseFormSet
from django import forms

from xml.etree.ElementTree import fromstring
from datetime import datetime

def home(request):
    form = AuthenticationForm()
    home_dict = {}
    if request.method == 'POST':
        if 'login' in request.POST:
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
        else:
            form = AuthenticationForm(form)
            c = RequestContext(request,{'form': form,})
            return render_to_response("home.html",c)
    if request.user.is_authenticated():
        try:
            NamecheapAccount.objects.all()[0].namecheap_username
        except:
            warning_message = "warning"
            home_dict.update({"warning":warning_message})
        return render_to_response("home.html",home_dict,context_instance = RequestContext(request))
    return render_to_response("home.html",{"form":form,},
        context_instance = RequestContext(request))


def config_domain_view(request):
    """This view shows input panel for domain config."""
    try:
        USER_NAME = NamecheapAccount.objects.all()[0].namecheap_username
        NAMECHEAP_API_KEY = NamecheapAccount.objects.all()[0].namecheap_api_key
    except:
        pass
    form = DomainConfigForm()
    if request.method == "POST":
        form = DomainConfigForm(request.POST)
        print "check before"
        print form
        data = requests.get('http://wtfismyip.com/json').json()
        my_ip = data['YourFuckingIPAddress']
        domain = request.POST.get("domain_name")
        subdomain = request.POST.get("subdomain_name")
        print subdomain
        frontend = request.POST.get("ip_address")
        ip_query_set = Ip_Address.objects.all()
        ip_list = []
        for ip_entry in ip_query_set:
            ip_list.append(ip_entry.ip_address)
        redirect = random.choice(ip_list)
        spf = 'v=spf1 a mx ip4:%s -all' % frontend
        mx = '%s.%s.' % (subdomain, domain)
        new = [
            record('*', 'A', redirect),
            record(subdomain, 'A', frontend),
            record('@', 'A', frontend),
            record('@', 'MX', mx),
            record('@', 'TXT', spf),
        ]
        api = Api(USER_NAME, NAMECHEAP_API_KEY, USER_NAME, my_ip, False, True)
        if form.is_valid():
            xml = api.domains_dns_setHosts(domain, new)
            domain_create = DomainModel.objects.create(domain_name=domain,
                            subdomain_name=subdomain, ip_address=frontend,
                            availability="nonavailable")
            domain_create.save()
            return view_dns_hosts(request,domain,subdomain,frontend)
        else:
            print "subdomain:" + str(subdomain)
            print "frontend:" + str(frontend)
            if subdomain != "" and frontend != "":
                print "yo"
                try:
                    domain_model = DomainModel.objects.get(domain_name=domain)
                    domain_model.subdomain = subdomain
                    domain_model.ip_address = frontend
                    domain_model.availability = "nonavailable"
                    domain_model.save()
                    xml = api.domains_dns_setHosts(domain, new)
                    return view_dns_hosts(request,domain,subdomain,frontend)
                except:
                    pass
            else:
                return render_to_response("landing/domain_config.html", {"form":form},
                    context_instance=RequestContext(request))
    #list domains from database
    domain_objects = DomainModel.objects.filter(availability="available")
    paginator = Paginator(domain_objects,7)
    print "hey"
    #PAGINATION CODE
    page = request.GET.get('page')
    try:
        domain_objects = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        domain_objects = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        domain_objects = paginator.page(paginator.num_pages)
    return render_to_response("landing/domain_config.html", {"form":form,"domains":domain_objects},
        context_instance=RequestContext(request))


def view_dns_hosts(request,domain="",subdomain="",ip=""):
    USER_NAME = NamecheapAccount.objects.all()[0].namecheap_username
    NAMECHEAP_API_KEY = NamecheapAccount.objects.all()[0].namecheap_api_key
    data = requests.get('http://wtfismyip.com/json').json()
    my_ip = data['YourFuckingIPAddress']
    if request.method == "GET":
        domain = request.GET.get("domain")
        subdomain = request.GET.get("subdomain")
        ip = request.GET.get("ip_address")
    api = Api(USER_NAME, NAMECHEAP_API_KEY, USER_NAME, my_ip, False, True)
    hosts = api.domains_dns_getHosts(domain)
    domain_id = DomainModel.objects.get(domain_name=domain).id
    return render_to_response("landing/view_hosts.html",
                    {"hosts":hosts,"ip":ip,"domain":domain,"subdomain":subdomain,"domain_id":domain_id},
                    context_instance=RequestContext(request))

def edit_domain(request):
    """Edit domain"""
    if request.method == "POST":
        domain = request.POST.get("domain_name")
        subdomain = request.POST.get("subdomain_name")
        ip_address = request.POST.get("ip_address")
        availability = request.POST.get("availability")
        domain_instance = DomainModel.objects.get(id=request.POST.get("id"))
        domain_instance.domain = domain
        domain_instance.subdomain = subdomain
        domain_instance.ip_address = ip_address
        domain_instance.availability = availability
        bl_dict = {"black_list":False}# check_blacklist(domain)
        if not bl_dict["black_list"] == True:
            domain_instance.save()
            return HttpResponseRedirect('/landing/view-domains/')
        else:
            DomainForm(instance=domain_instance)
            return render_to_response("landing/edit_domain.html",
                        {"form":form,"bl_dict":bl_dict},
                    context_instance=RequestContext(request))

    else:
        domain_id = request.GET.get("id")
        domain_obj = DomainModel.objects.get(id=domain_id)
        print domain_obj.availability
        print "asdasdas"
        form = DomainForm(initial={"domain_name":domain_obj.domain_name,
                                   "subdomain_name":domain_obj.subdomain_name,
                                   "ip_address":domain_obj.ip_address,
                                   "availability":domain_obj.availability})
        print form
        return render_to_response("landing/edit_domain.html",
                        {"form":form,"domain_entry":domain_obj},
                    context_instance=RequestContext(request))

def add_node(request):
    """
        This function is responsible for the add node view.
        The same view accepts post request from the page and adds
        nodes to the database.
    """
    if request.method == "POST": #if submit button is clicked, it enters here
        form = VpsnodeForm(request.POST)
        if form.is_valid():
            check_bl_result = check_blacklist(str(request.POST.get("domain_name")))
            check_reverse_result = check_reverse(str(request.POST.get("reverse_domain")),
                                   str(request.POST.get("ip_address")))
            print check_bl_result, check_reverse_result
            if (not check_bl_result["black_list"]) and check_reverse_result["match"]:
                vps_object = form.save() #save to database
                form_dict = {
                                "ip_address":str(request.POST.get("ip_address")),
                                "domain_name":str(request.POST.get("domain_name")),
                                "reverse_domain":str(request.POST.get("reverse_domain")),
                                "host_url":str(request.POST.get("host_url")),
                                "account_email":str(request.POST.get("account_email")),
                                "account_password":str(request.POST.get("account_password")),
                                "root_password":str(request.POST.get("root_password")),
                                "cpanel_url":str(request.POST.get("cpanel_url")),
                                "cpanel_username":str(request.POST.get("cpanel_username")),
                                "cpanel_password":str(request.POST.get("cpanel_password")),
                                "price":str(request.POST.get("price")),
                                "notes":str(request.POST.get("notes")),
                                "comment":str(request.POST.get("comment")),
                                "status":str(request.POST.get("status")),
                }
                form_values = [
                                str(form_dict["ip_address"]),
                                str(form_dict["domain_name"]),

nikolaproject/templates/landing/add_domain.html
{% extends "index.html" %}
{% block adddomain_active %} active {% endblock %}
{% block content %}
		<div class="panel panel-primary">
		<div class="panel-heading">Add Domain</div>
		<div class="clearfix visible-xs"></div>
		<div class="panel-body">
			{% if bl_dict.black_list %}
				<div class="col-md-8 col-md-offset-2">
					<p class="text-error">{{ bl_dict.result }}</p>
				</div>
			{% endif %}
			<form action="/landing/add-domain/" method="post">
				{% csrf_token %}
				<p class="text-error">{{ form.domain_name.errors.as_text }}</p>
				<table class="table table-bordered">
					{{ form.as_table }}
				</table>
				<input type="submit" class="btn btn-primary" value="Add Domain" />
				<a class="btn btn-primary" href="/landing/add-domain-bulk/">Bulk add</a>
			</form>
		</div>
	</div>
{% endblock %}

nikolaproject/templates/landing/add_domain_set.html
{% extends "index.html" %}
{% block adddomain_active %} active {% endblock %}
{% block extra_head %}
	<script type="text/javascript">
		$(document).ready(function () {
			$('#set_field_btn').click(function(){
				page = $('.nmbr_fld').val();
				if (!isNaN(page)){
					window.location = "/landing/add-domain-bulk/?extra="+page;
				}
				else{
					alert("Input a valid number");
				}
			});
			$('#add_field_btn').click(function(){
				var num_fields = parseInt($("#id_form-TOTAL_FORMS").val());
				$("#id_form-TOTAL_FORMS").val(num_fields+1);
				var row = $("#row1").clone(true).get(0);
				row.setAttribute("id", "row"+(num_fields+1));
				$(row).children().children().each(function(){
					this.id = this.id.replace("0",num_fields);
					this.value = "";
					try{
						this.name = this.name.replace("0",num_fields);

					}
					catch(e){}
				});
				$("#table").append(row);
			});
			$('#remove_field_btn').click(function(){
				var num_fields = parseInt($("#id_form-TOTAL_FORMS").val());
				if(num_fields >2){
					$("#id_form-TOTAL_FORMS").val(num_fields-1);
					$("#row"+num_fields).remove();
					console.log($("#myform").serialize());
				}

			});
		});
	</script>
{% endblock %}
{% block content %}
		<div class="panel panel-primary">
		<div class="panel-heading">Add Domain</div>
		<div class="clearfix visible-xs"></div>
		<div class="panel-body">
			
			<div class="col-md-12">
<tr>
					    	 <!--<td>
								<label>Number of fields: </label>
							</td>
							<td><input class="nmbr_fld" />&nbsp;&nbsp;<a id="set_field_btn" class="btn btn-primary btn-sm">Set # of fields</a></td>-->
							<a class="btn btn-primary btn-sm" id="add_field_btn" href="#">Add Field</a>
							<a class="btn btn-danger btn-sm" id="remove_field_btn" href="#">Remove Field</a>
						</tr>
				<form id="myform" action="/landing/add-domain-bulk/" method="post">
				    <table class="table" id="table">

					{% csrf_token %}
				    	<tr>
				    		<th>Domain</th>
				    		<th>Subdomain</th>
				    	</tr>
				    	{{ formset.management_form }}
				        {% for form in formset %}
				        	<tr id="row{{forloop.counter}}">
				        		<td>{{ form.domain_name }}<p name="form-par-{{forloop.counter}}" class="text-danger">{{ form.domain_name.errors.as_text }}</p></td>
				        		<td>{{ form.availability }}</td>
				        	</tr>

				        	
				        {% endfor %}
				        <div class="bs-callout bs-callout-danger">		<p class="text-danger">{{ formset.non_form_errors.as_text }}</p>
				        </div>
				    </table>
					<input type="submit" class="btn btn-primary btn-sm" value="Add Domains" />
				</form>
			</div>

		</div>
	</div>
{% endblock %}

nikolaproject/templates/landing/add_node.html
{% extends "index.html" %}
{% block node_active %} active {% endblock %}
{% block content %}
	<div class="panel panel-primary">
		<div class="panel-heading clearfix">Add VPS Node</div>
		{% if notice.error_message and notice.error_message.strip %}
			<div class="alert alert-success">
				{{ notice.success_message }}
			</div>
		{% elif notice.success_message and notice.success_message.strip %}
			<div class="alert alert-danger">
				{{ notice.error_message }}
			</div>
		{% else %}
		{% endif %}
		{% if bl_result.black_list %}
			<div class="alert alert-danger">
				The domain you entered is blacklisted.
				<p>{{ bl_result.result }}</p>
			</div>
		{% endif %}
		{% if rev_result.gethosterror %}
			<div class="alert alert-danger">
				<p>{{ rev_result.error_message }}</p>
			</div>
		{% elif rev_result.match %}
			<div class="alert alert-danger">
				<p>{{ rev_result.check_message }}</p>
			</div>
		{% endif %}
		<div class="panel-body">
			<div class="clearfix"></div>
			<p>Add your VPS Nodes here.</p>
			<form action="/landing/add-node/" method="post">
				{% csrf_token %}
				<table class="table">
					<tr>
						<td>{{ form.ip_address.label }}</td>
						<td>{{ form.ip_address }} 
								<small class="red_font">{{form.ip_address.errors.as_text}}</small>
						</td>
						<td>{{ form.domain_name.label }}</td>
						<td>{{ form.domain_name }} 
							<small class="red_font">{{form.domain_name.errors.as_text}}</small></td>
					</tr>
					<tr>
						<td>{{ form.reverse_domain.label }}</td>
						<td>{{ form.reverse_domain }} 
							<small class="red_font">{{form.domain.errors.as_text}}</small></td>
						<td>{{ form.host_url.label }}</td>
						<td>{{ form.host_url }}
							<small class="red_font">{{form.host_url.errors.as_text}}</small>
						</td>
					</tr>
					<tr>
						<td>{{ form.account_email.label }}</td>
						<td>{{ form.account_email }} <small class="red_font">{{form.account_email.errors.as_text}}</small></td>
						<td>{{ form.account_password.label }}</td>
						<td>{{ form.account_password }}</td>
					</tr>
					<tr>
						<td>{{ form.root_password.label }}</td>
						<td>{{ form.root_password }}</td>
						<td>{{ form.cpanel_url.label }}</td>
						<td>{{ form.cpanel_url }} <small class="red_font">{{form.cpanel_url.errors.as_text}}</small></td>
					</tr>
					<tr>
						<td>{{ form.cpanel_username.label }}</td>
						<td>{{ form.cpanel_username }}</td>
						<td>{{ form.cpanel_password.label }}</td>
						<td>{{ form.cpanel_password }}</td>
					</tr>
					<tr>
						<td>{{ form.price.label }}</td>
						<td>{{ form.price }}</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td>{{ form.notes.label }}</td>
						<td colspan="3">{{ form.notes }}</td>
					</tr>
					<tr><td colspan="4">-------------</td></tr>
					<tr><td>{{ form.comment.label }}</td><td>{{ form.comment }}</td><td>{{ form.status.label }}</td><td>{{ form.status }}</td></tr>
				</table>
				<input type="submit" class="btn btn-primary" value="Add Node" />
			</form>
		</div>
	</div>
	{{ try }}
{% endblock %}

nikolaproject/templates/landing/domain_config.html
{% extends "index.html" %}
{% block domainconf_active %} active {% endblock %}
{% block extra_head %}
    <script type="text/javascript">
        $(document).ready(function () {
        	$('.configure_btn').click(function(){
        		var domain_data = $(this).data("domain");
        		var subdomain_data = $(this).data("subdomain");
        		var ip_address_data = $(this).data("ipaddress");
        		console.log(ip_address_data);
        		if ((subdomain_data != "None") && (ip_address_data != "None")){
	        		$.post( 
			            "/landing/config-domain/",
			            { domain: domain_data,subdomain:subdomain_data,
			            ip_address:ip_address_data,"csrfmiddlewaretoken" :getCookie('csrftoken') },
			            function(data){
			            	window.location = "/landing/view-dns-hosts/?domain="+domain_data+"&subdomain="+subdomain_data+"&ip_address="+ip_address_data;
			            }
			        );
        		}
        		else{
        			$("#id_domain_name").val(domain_data);
        		}
        	});
        	$(".view_btn").click(function(){
        		window.location = $(this).data("url");
        	});
        });
		function getCookie(name) {
	        var cookieValue = null;
	        if (document.cookie && document.cookie != '') {
	            var cookies = document.cookie.split(';');
	            for (var i = 0; i < cookies.length; i++) {
	                var cookie = jQuery.trim(cookies[i]);
	                // Does this cookie string begin with the name we want?
	                if (cookie.substring(0, name.length + 1) == (name + '=')) {
	                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
	                    break;
	                }
	            }
	            return cookieValue;
	        }
	    }
    </script>
{% endblock %}
{% block content %}
<div class="panel panel-primary">
	<div class="panel-heading">Domain configuration</div>
	<div class="panel-body row">
		<div class="col-md-12">
			<p>List of available domains</p>
		</div>
		<div class="clearfix"></div>
		{% if domains %}
		<div class="col-md-12">
			<table class="table table-bordered">
				<tr>
					<th>Domain name</th>
					<th>Subdomain</th>
					<th>IP Address</th>
					<th>Availability</th>
					<th>Controls</th>
				</tr>
				{% for domain in domains %}
					<tr>
						<td>{{ domain.domain_name }}</td>
						<td>{{ domain.subdomain_name }}</td>
						<td>{{ domain.ip_address }}</td>
						<td>{{ domain.availability }}</td>
						<td><button class="btn btn-primary btn-xs configure_btn" data-domain="{{ domain.domain_name }}" data-subdomain="{{ domain.subdomain_name }}"  data-ipaddress={{ domain.ip_address }}>Configure</button>
						{% if domain.availability == "nonavailable" %}
							<button class="view_btn btn btn-warning btn-xs" data-url="/landing/view-dns-hosts/?domain={{domain.domain_name}}&subdomain={{domain.subdomain_name}}&ip_address={{domain.ip_address}}">View info</button>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</table>
			<div class="col-md-4 col-md-offset-5">
				<div class="pagination">
				    <span class="step-links">
				        {% if domains.has_previous %}
				            <a href="?page={{ domains.previous_page_number }}">previous</a>
				        {% endif %}

				        <span class="current">
				            Page {{ domains.number }} of {{ domains.paginator.num_pages }}
				        </span>

				        {% if domains.has_next %}
				            <a href="?page={{ domains.next_page_number }}">next</a>
				        {% endif %}
				    </span>
				</div>
			</div>
		</div>
		{% endif %}

		<div class="col-md-4 col-md-offset-4">
			<form action="/landing/config-domain/" method="post">
				{% csrf_token %}
				<table class="table table-bordered">
					<tr>
						<td>{{ form.ip_address.label }}</td>
						<td>{{ form.ip_address }} 
							<p class="text-error"><small>{{ form.ip_address.errors.as_text }}</small></p>
						</td>
					</tr>
					<tr>
						<td>{{ form.domain_name.label }}</td>
						<td>{{ form.domain_name }}
							<p class="text-error"><small>{{ form.domain_name.errors.as_text }}</small></p>
						</td>
					</tr>
					<tr>
						<td>{{ form.subdomain_name.label }}</td>
						<td>{{ form.subdomain_name }}
							<p class="text-error"><small>{{ form.subdomain_name.errors.as_text }}</small></p>
						</td>
					</tr>
				</table>
				<input type="submit" class="btn btn-primary" value="Configure " />
			</form>
		</div>
	
	</div>
	
</div>
{% endblock %}

nikolaproject/templates/landing/view_hosts.html
{% extends "index.html" %}
{% block domainconf_active %} active {% endblock %}
{% block content %}
<div class="panel panel-primary">
	<div class="panel-heading">Domain hosts</div>
	<div class="panel-body">
		<div class="clearfix"></div>
		<div class="alert alert-success">
			Domain: {{ domain }}, 
			IP Address: {{ ip }},
			Subdomain: {{ subdomain }},
		</div>
		<form action="/landing/config-domain/" method="post">
			{% csrf_token %}
			<table class="table table-bordered">
				<tr>
					<th> HOST ID </th>
					<th> NAME </th>
					<th> ADDRESS </th>
					<th> RECORD TYPE </th>
					<th> MX PREF </th>
					<th> TTL </th>					
				</tr>
				{% for host in hosts %}
					<tr>
						<td>{{ host.HostId }}</td>
						<td>{{ host.Name }}</td>
						<td>{{ host.Address }}</td>
						<td>{{ host.Type }}</td>
						<td>{{ host.MXPref }}</td>
						<td>{{ host.TTL }}</td>
					</tr>
				{% endfor %}
				<tr>
			</table>
		</form>
		<div class="col-md-4">
			<a href="/landing/edit-domain/?id={{domain_id}}">Edit</a>
		</div>
	</div>
</div>
{% endblock %}